name: Build Android aarch64

on: [push, pull_request]

jobs:
  build-android-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build android-aarch64
      run: |
        chmod +x waf
        chmod +x scripts/build-android-aarch64.sh
        ./scripts/build-android-aarch64.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: android_aarch64_build
        path: android_aarch64_build
        if-no-files-found: error
        retention-days: 7

    - name: Upload artifacts 2
      uses: actions/upload-artifact@v7.0.1
      with:
        name: android_aarch64_build_configlog
        path: ./build
        if-no-files-found: error
        retention-days: 7
