name: Build Linux AMD64

on: [push, pull_request]

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        chmod +x waf
        chmod +x scripts/build-ubuntu-amd64.sh
        ./scripts/build-ubuntu-amd64.sh
