name: Telegram Notify
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новое изменение от ${{ github.actor }} (${{ github.sha }}) 
            ${{ github.event.head_commit.message }}
