name: Build Win32

on: [push, pull_request]

jobs:
  build-windows-i386:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        python waf configure -T release --32bits --enable-speex --enable-opus --build-games=cstrike --prefix=./win32_build
        python waf install
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: win32_build
        path: win32_build
        if-no-files-found: error
        retention-days: 7