name: Build Win64

on: [push, pull_request]

jobs:
  build-windows-amd64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        python waf configure -T release --enable-speex --enable-opus --build-games=cstrike --prefix=./win64_build
        python waf install
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: win64_build
        path: win64_build
        if-no-files-found: error
        retention-days: 7
